
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "toy_example",
    srcs = ["toy_example.cc"],
    deps = ["@lapackpp//:lapackpp"]
)
